#include <stdio.h>
#include <stdlib.h>

#include "pico/stdlib.h"
#include "hardware/pio.h"
#include "hardware/clocks.h"
#include "ws2812.pio.h"

#define IS_RGBW true        // Will use RGBW format
#define NUM_PIXELS 1        // There is 1 WS2812 device in the chain
#define WS2812_PIN 28       // The GPIO pin that the WS2812 connected to

int player_lives = 3;       // Player has 3 lives to start with
int correct_answers = 0;    // Player has 0 correct answers to start with
int lives_added = 0;        // Player has 0 lives added to start with
int lives_lost = 0;         // Player has 0 lives lost to start with


/**
 * @brief Wrapper function used to call the underlying PIO
 *        function that pushes the 32-bit RGB colour value
 *        out to the LED serially using the PIO0 block. The
 *        function does not return until all of the data has
 *        been written out.
 * 
 * @param pixel_grb The 32-bit colour value generated by urgb_u32()
 */
static inline void put_pixel(uint32_t pixel_grb) {
    pio_sm_put_blocking(pio0, 0, pixel_grb << 8u);
}


/**
 * @brief Function to generate an unsigned 32-bit composit GRB
 *        value by combining the individual 8-bit parameters for
 *        red, green and blue together in the right order.
 * 
 * @param r     The 8-bit intensity value for the red component
 * @param g     The 8-bit intensity value for the green component
 * @param b     The 8-bit intensity value for the blue component
 * @return uint32_t Returns the resulting composite 32-bit RGB value
 */
static inline uint32_t urgb_u32(uint8_t r, uint8_t g, uint8_t b) {
    return  ((uint32_t) (r) << 8)  |
            ((uint32_t) (g) << 16) |
            (uint32_t) (b);
}

// Update RGB LED colour  
void RGB_update(int number_of_lives)
{
    switch (number_of_lives)                                // Switch statement to update RGB LED colour based on number of lives remaining
    {
        case 0:                                             // If player has 0 lives remaining
            // Black
            put_pixel(urgb_u32(0x00, 0x00, 0x00));
            printf("0 lives remaining. GAME OVER");
            break;

        case 1:                                             // If player has 1 life remaining
            // Red
            put_pixel(urgb_u32(0xFF, 0x00, 0x00));
            printf("1 life remaining");
            break;

        case 2:                                             // If player has 2 lives remaining
            // Yellow
            put_pixel(urgb_u32(0xFF, 0xFF, 0x00));
            printf("2 lives remaining");
            break;

        case 3:                                             // If player has 3 lives remaining (Max)
            // Green
            put_pixel(urgb_u32(0x00, 0xFF, 0x00));
            printf("3 lives remaining");
            break;

        default:
            printf("");
            break;
    }

}

// Update player lives 
void update_lives(bool answer_entered)                          // Function to update player lives based on whether the answer entered was correct or not
{
    if (answer_entered == true)                                 // If the answer entered was correct
    {
        printf("Correct. Life Added")                           // Add a life to the player
    
        lives_added++;
        correct_answers++;
        if (player_lives == 3)                                  // If the player has 3 lives(max number of lives), do not add another life
        {
            printf("Max Lives Reached");
        }
        else                                                    // If the player has less than 3 lives, add a life
        {
            player_lives += 1;
            RGB_update(player_lives);
        }
    }
    else                                                        // If the answer entered was incorrect
    {
        printf("Incorrect. Life Lost");                         // Deduct a life from the player
        correct_answers--;
        lives_lost++;
        player_lives -= 1;
        RGB_update(player_lives);
    }
}

/**
 * @brief EXAMPLE - WS2812_RGB
 *        Simple example to initialise the NeoPixel RGB LED on
 *        the MAKER-PI-PICO and then flash it in alternating
 *        colours between red, green and blue forever using
 *        one of the RP2040 built-in PIO controllers.
 * 
 * @return int  Application return code (zero for success).
 */
int main() {
 
    // Initialise all STDIO as we will be using the GPIOs
    stdio_init_all();
 
    // Initialise the PIO interface with the WS2812 code
    PIO pio = pio0;
    uint offset = pio_add_program(pio, &ws2812_program);
    ws2812_program_init(pio, 0, offset, WS2812_PIN, 800000, IS_RGBW);

    // Do forever...
    while(true) {

        // Set the color to red at half intensity
        put_pixel(urgb_u32(0x7F, 0x00, 0x00));
        sleep_ms(500);

        // Set the color to green at half intensity
        put_pixel(urgb_u32(0x00, 0x7F, 0x00));
        sleep_ms(500);

        // Set the color to blue at half intensity
        put_pixel(urgb_u32(0x00, 0x00, 0x7F));
        sleep_ms(500);

    }

    // Should never get here due to the infinite while-loop.
    return 0;

}